repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.1
  hooks:
  - id: clang-format
    types_or: [c++, c]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending

- repo: https://github.com/cpplint/cpplint
  rev: "1.6.1"
  hooks:
  - id: cpplint

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    exclude: |
      (?x)^(
          STM32F401.svd
      )$
