repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v17.0.5
  hooks:
  - id: clang-format
    types_or: [c++, c]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: end-of-file-fixer
  - id: mixed-line-ending

- repo: https://github.com/cpplint/cpplint
  rev: "1.6.1"
  hooks:
  - id: cpplint

- repo: https://github.com/crate-ci/typos
  rev: v1.16.23
  hooks:
  - id: typos
    args:
      [] # Do not auto-fix
    exclude: |
      (?x)^(
          STM32F401.svd|
      )$
