name: CI - build C application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
      uses: carlosperate/arm-none-eabi-gcc-action@v1
    - run: arm-none-eabi-gcc --version
    
    - name: Build application
      run: make -j
      
    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build artifacts
        path: |
          build/*.hex
          build/*.elf
